// Auto-generated by `supabase gen types typescript` — do not edit by hand.
// Run: npx supabase gen types typescript --project-id <your-project-id> > packages/db/src/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
